### ISSUE TITLE
BIST has error with multiple roots in a sentence

### ISSUE THREAD

**Issue by fallcat** [NervanaSystems/nlp-architect#6]
I found these two datasets in English and Chinese: 
https://github.com/UniversalDependencies/UD_English-EWT
https://github.com/UniversalDependencies/UD_Chinese-GSD
and tested them with BIST. 

However, this error occurs after a few thousand batches of training for both:
`nlp_architect.models.bist.eval.conllu.conll17_ud_eval.UDError: There are multiple roots in a sentence`
I have checked the training data and the number of roots is same as number of sentences in each train/dev/test set. Do you know what might cause the problem and how to fix it? Or do you have dataset that works and we can use it?

Thank you very much!

**Comment by fallcat** [comment]
It seems that some sentences in the generated dev_epoch_2_pred.conllu file have multiple roots... not the original data. This means the problem is with the parser

**Comment by danielkorat** [comment]
Hi,
Thanks for the feedback.
From my experience, this issue arrises when the training data size is insufficient. Info from the original author on this issue can be found [here](https://github.com/elikip/bist-parser/issues/10).
The BIST training was tested on [PTB-3](https://catalog.ldc.upenn.edu/ldc99t42)'s WSJ section, converted to UD v1 (~30MB) using [Stanford Parser](https://nlp.stanford.edu/software/stanford-dependencies.shtml) as per Section 4.1 of this [paper](https://cs.stanford.edu/~danqi/papers/emnlp2014.pdf). This training data can't be shared due to LDC's [licensing](https://catalog.ldc.upenn.edu/license/ldc-non-members-agreement.pdf).
I suggest obtaining this license and reproducing the above dataset yourself or merging multiple English UD treebanks found [here (v2)](http://universaldependencies.org/) or [here (v1)](http://universaldependencies.org/) or on github repos.

**Comment by danielkorat** [comment]
I only know the sources which I linked above (LDC, UD website, github files).

**Comment by fallcat** [comment]
Thank you!
