### ISSUE TITLE
Training an existing NER  model with new data having additional entities

### ISSUE THREAD

**Issue by LivingScripts** [NervanaSystems/nlp-architect#64]
#### Can I train an existing NER model with a new dataset so that it can recognize additional entities, so that it can recognize existing as well as new entities.

**Comment by peteriz** [comment]
Hi @LivingScripts, do you mean that you have a pre-trained NER model with N entities and want to train it further, with new data and M new entities, so that it will recognize M+N entities?
If so, NLP Architect supports only training models from scratch, meaning, you'll have to train a new model with all the data you have (old+new).
Even if NLP Architect will support such scenario (of an additional train phase), you will probably deal with catastrophic forgetting (the model will start to forget things it learned from the old data and might fail to classify old data correctly). For that purpose, you'll have to use all the data you have in training.

**Comment by LivingScripts** [comment]
exactly what I was after, thanks
